name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 2.1
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
      id: fossa-analyze
      with:
        api-key: ${{secrets.FOSSA_API_KEY}}
        
    - run: |
        echo "this is the java version"
        java -version
